### ISSUE TITLE
Install PYRO-NN-Layers through Anaconda?

### ISSUE THREAD

**Issue by rodrigovimieiro** [csyben/PYRO-NN-Layers#4]
I saw that to use [PYRO-NN](https://github.com/csyben/PYRO-NN), it is required to build PYRO-NN-Layers into the Tensorflow package. I use Python and Tensorflow through Anaconda, and the [building instructions](https://www.tensorflow.org/install/source_windows) use pip package.

Is there a way to build PYRO-NN-Layers through Anaconda on Windows? I am a python beginner, so sorry if the question is too dumb.

My system configurations are:
- Windows 10.
- Anaconda 3
- Conda 4.7.11
- Python 3.6

Thank you!

**Comment by csyben** [comment]
Hi,
i would like to support windows from the scratch, and actual it is possible to ship the PYRO-NN-Layers for Windows. Currently you have to prepare the binary by your self. If you follow the guide on how to build Tensorflow sources on Windows it self [1], and get this running, than the rest is very easy. One way suggested by Tensorflow would be build Tensorflow with bazel as described in [2], and just copy the PYRO-NN-Layer files within the example ops section from Tensorflow.

I am sorry that i can not support you with a well written guide nor a pre compiled binary for Windows (which is in planning). One point on my to-do list is to provide binaries for Windows and Ubuntu or better to directly ship the correct Layers via pip. But this will take to the end of 2019 until we will reach this state.

best,
Christopher

[1] https://www.tensorflow.org/install/source_windows
[2]

**Comment by rodrigovimieiro** [comment]
Hi, 

I actually switched to Ubuntu. I am following the building instructions for Linux and I let you know if it works properly.  

For future references, this table ([Linux](https://www.tensorflow.org/install/source#linux), [Windows](https://www.tensorflow.org/install/source_windows#gpu)) is **extremely useful** for who are intending to build TensorFlow from source. Make sure Bazel is at the correct version, and also CUDA and the other dependencies. 

Also, for Windows, there are these [instructions](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12) that someone might find it useful.

Thanks for the reply!!
